import TourImg2 from '../assets/images/TourImg2.png';
import TourImg3 from '../assets/images/TourImg3.png';
import TourImg4 from '../assets/images/TourImg4.png';
import TourImg5 from '../assets/images/TourImg5.png';

const AGENT_TYRONE = {
  name: 'Tyrone Boyer',
  email: 'tyroneboyer@gmail.com',
  phone: '480-221-1885',
};

export const MY_TOURS_DATA = [
  {
    id: 'b-001',
    name: 'Tropical Caribe',
    location: 'Punta Cana, Dominican Republic',
    image: TourImg2,
    status: 'booked',
    startDate: '2025-01-15',
    duration: 7,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 0,
    agent: AGENT_TYRONE,
    canceledBy: null,
    cancelReason: null,
    hasReview: false,
    canceledAfterStep: null,
    freeCancellationDate: '2026-06-01',
    maxGuests: 2,
  },
  {
    id: 'b-002',
    name: 'Jungle Villa',
    location: 'Bali, Indonesia',
    image: TourImg3,
    status: 'confirmed',
    startDate: '2025-02-15',
    duration: 7,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 2,
    agent: AGENT_TYRONE,
    canceledBy: null,
    cancelReason: null,
    hasReview: false,
    canceledAfterStep: null,
    freeCancellationDate: '2025-01-05',
    maxGuests: 4,
  },
  {
    id: 'b-003',
    name: 'Tropical Caribe',
    location: 'Punta Cana, Dominican Republic',
    image: TourImg2,
    status: 'started',
    startDate: null,
    duration: null,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 2,
    agent: AGENT_TYRONE,
    canceledBy: null,
    cancelReason: null,
    hasReview: false,
    canceledAfterStep: null,
    maxGuests: 2,
  },
  {
    id: 'b-004',
    name: 'Tropical Caribe',
    location: 'Punta Cana, Dominican Republic',
    image: TourImg2,
    status: 'finished',
    startDate: '2023-02-25',
    duration: 12,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 2,
    agent: AGENT_TYRONE,
    canceledBy: null,
    cancelReason: null,
    hasReview: true,
    canceledAfterStep: null,
    maxGuests: 2,
  },
  {
    id: 'b-005',
    name: 'Riverside Resort',
    location: 'Ao Nang, Thailand',
    image: TourImg4,
    status: 'canceled',
    startDate: '2025-01-04',
    duration: 7,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 2,
    agent: AGENT_TYRONE,
    canceledBy: 'Travel agent',
    cancelReason: 'Hotel emergency',
    hasReview: false,
    canceledAfterStep: 1,
    maxGuests: 3,
  },
  {
    id: 'b-006',
    name: 'Riverside Resort',
    location: 'Ao Nang, Thailand',
    image: TourImg5,
    status: 'canceled',
    startDate: '2025-01-04',
    duration: 7,
    mealPlan: 'Breakfast (BB)',
    traveler: 'Johnson Doe',
    travelerCount: 1,
    totalPrice: 1400,
    documentsUploaded: 2,
    agent: AGENT_TYRONE,
    canceledBy: 'Tourist',
    cancelReason: '',
    hasReview: false,
    canceledAfterStep: 1,
    maxGuests: 3,
  },
];
