package com.epam.edp.demo.config;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import jakarta.annotation.PostConstruct;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.Properties;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

@Slf4j
@Data
@Configuration
@ConfigurationProperties(prefix = "jwt")
public class JwtConfig {

    private static final int DEFAULT_ACCESS_TOKEN_EXPIRY = 900;    // 15 minutes
    private static final int DEFAULT_REFRESH_TOKEN_EXPIRY = 604800; // 7 days
    private static final int RSA_KEY_SIZE_BITS = 2048;
    private static final String DEV_KEYS_FILE = ".jwt-dev-keys.properties";

    private String privateKey;
    private String publicKey;
    private int accessTokenExpiry = DEFAULT_ACCESS_TOKEN_EXPIRY;
    private int refreshTokenExpiry = DEFAULT_REFRESH_TOKEN_EXPIRY;

    private PrivateKey rsaPrivateKey;
    private PublicKey rsaPublicKey;

    @PostConstruct
    public void init() {
        boolean keysProvided = false;

        if (privateKey != null && !privateKey.isBlank()) {
            this.rsaPrivateKey = parsePrivateKey(privateKey);
            log.info("RSA private key loaded successfully");
            keysProvided = true;
        }

        if (publicKey != null && !publicKey.isBlank()) {
            this.rsaPublicKey = parsePublicKey(publicKey);
            log.info("RSA public key loaded successfully");
            keysProvided = true;
        }

        if (!keysProvided) {
            log.warn("JWT keys not configured — generating ephemeral RSA key pair for DEVELOPMENT ONLY");
            log.warn("⚠️  DO NOT use auto-generated keys in production!"
                    + " Set JWT_PRIVATE_KEY and JWT_PUBLIC_KEY env vars.");
            loadOrGenerateDevKeyPair();
        }
    }

    private void loadOrGenerateDevKeyPair() {
        Path keyFile = Paths.get(DEV_KEYS_FILE).toAbsolutePath().normalize();

        if (loadDevKeyPairFromFile(keyFile)) {
            return;
        }

        generateDevKeyPair();
        saveDevKeyPairToFile(keyFile);
    }

    private void generateDevKeyPair() {
        try {
            KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
            generator.initialize(RSA_KEY_SIZE_BITS);
            KeyPair keyPair = generator.generateKeyPair();
            this.rsaPrivateKey = keyPair.getPrivate();
            this.rsaPublicKey = keyPair.getPublic();
            log.info("Ephemeral RSA-2048 key pair generated for dev mode");
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("Failed to generate dev RSA key pair", e);
        }
    }

    private boolean loadDevKeyPairFromFile(Path keyFile) {
        if (!Files.exists(keyFile)) {
            return false;
        }

        Properties props = new Properties();
        try (InputStream in = Files.newInputStream(keyFile)) {
            props.load(in);
            String privateKeyValue = props.getProperty("jwt.private-key", "");
            String publicKeyValue = props.getProperty("jwt.public-key", "");

            if (privateKeyValue.isBlank() || publicKeyValue.isBlank()) {
                log.warn("Dev JWT key file exists but is incomplete: {}", keyFile);
                return false;
            }

            this.rsaPrivateKey = parsePrivateKey(privateKeyValue);
            this.rsaPublicKey = parsePublicKey(publicKeyValue);
            log.info("Loaded persistent development JWT key pair from {}", keyFile);
            return true;
        } catch (IOException | IllegalStateException e) {
            log.warn("Failed to load development JWT key pair from {}. A new key pair will be generated.", keyFile, e);
            return false;
        }
    }

    private void saveDevKeyPairToFile(Path keyFile) {
        try {
            Properties props = new Properties();
            props.setProperty("jwt.private-key", Base64.getEncoder().encodeToString(rsaPrivateKey.getEncoded()));
            props.setProperty("jwt.public-key", Base64.getEncoder().encodeToString(rsaPublicKey.getEncoded()));

            try (OutputStream out = Files.newOutputStream(keyFile)) {
                props.store(out, "Development JWT keys generated by JwtConfig");
            }

            log.info("Saved persistent development JWT key pair to {}", keyFile);
        } catch (IOException e) {
            log.warn("Failed to persist development JWT key pair to {}", keyFile, e);
        }
    }

    private PrivateKey parsePrivateKey(String pem) {
        try {
            String cleaned = pem
                    .replace("-----BEGIN PRIVATE KEY-----", "")
                    .replace("-----END PRIVATE KEY-----", "")
                    .replaceAll("\\s+", "");
            byte[] decoded = Base64.getDecoder().decode(cleaned);
            PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(decoded);
            return KeyFactory.getInstance("RSA").generatePrivate(spec);
        } catch (java.security.spec.InvalidKeySpecException
                | java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("Failed to parse RSA private key", e);
        }
    }

    private PublicKey parsePublicKey(String pem) {
        try {
            String cleaned = pem
                    .replace("-----BEGIN PUBLIC KEY-----", "")
                    .replace("-----END PUBLIC KEY-----", "")
                    .replaceAll("\\s+", "");
            byte[] decoded = Base64.getDecoder().decode(cleaned);
            X509EncodedKeySpec spec = new X509EncodedKeySpec(decoded);
            return KeyFactory.getInstance("RSA").generatePublic(spec);
        } catch (java.security.spec.InvalidKeySpecException
                | java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("Failed to parse RSA public key", e);
        }
    }
}

